### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by nimrodcoinso** [coinso/coinso-local-business-customizer#2]
Add individual social option for each city

[schema yelp="URL" facebook="URL" twitter="URL"] etc....

**Comment by barbareshet** [comment]
feature already exist in the shortcode.
Please try doing the follow:
Set up the main facebook ling from the customizer (not required)
on your local page, use the facebook attribute and provide it with the relevant link (as seen bellow)
[schema facebook="https://www.facebook.com/new-page"]
save
check page to see if the link was updated.

thanks
